"""new fields in user model

Revision ID: 66489fe14ed9
Revises: d91fc408b26b
Create Date: 2019-10-26 22:16:40.834861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66489fe14ed9'
down_revision = 'd91fc408b26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
